package com.thou.loosecoupling.di.v3finalfantasy;

public interface NotiService {
    //INTERFACE LA 1 CLASS CHA KO CO CODE TRONG CAC HAM (ABSTRACT METHOD),
    // SAU NAY CO CODE NHUNG NO LA LAM, TINH SAU

    //VE LI THUYET KO CO CODE THI KO NEW DC OBJECT VI NEW XONG CHAM GOI HAM, HAM KHONG CO CODE LAY GI MA CHAY

    //VE THUC TE, INTERFACE DC VI NHU CLB, HOI NHOM, GROUP, KHI NO TU TAP AE CUNG CHI HUONG, CUNG THEO NOI QUY, QUY TAC MA CLB DUA RA YEU CAU AE MEMBER PHAI TUAN THU
    //AE TUAN THU, LAM THEO CACH CUA MOI NGUOI, GOI LA IMPLEMENT - THI TRIEN, TRIEN KHAI

    //NO SE MOC SANG NGUYEN LI: TINH DA HINH - POLYMORPHISM, TU 1 RA NHIEU

    public void sendNoti(String to, String message);  //ham ko co code, cho ae member, class con trien khai va thuc thi

    //INTERNET NOI: HAM NAY CHINH LA CAI HOP DONG, CONTRACT MA CAC AE PHAI TUAN THU
}
